#pragma once

#ifdef ENCODER_ENABLE

#ifdef ENCODER_DIRECTION_FLIP
#undef ENCODER_DIRECTION_FLIP
#endif

#ifdef ENCODERS_PAD_A
#undef ENCODERS_PAD_A
#endif

#ifdef ENCODERS_PAD_B
#undef ENCODERS_PAD_B
#endif

#ifdef ENCODER_RESOLUTION
#undef ENCODER_RESOLUTION
#endif

#ifdef ENCODER_RESOLUTIONS
#undef ENCODER_RESOLUTIONS
#endif

#ifdef ENCODER_DIRECTION_FLIP_RIGHT
#undef ENCODER_DIRECTION_FLIP_RIGHT
#endif

#ifdef ENCODERS_PAD_A_RIGHT
#undef ENCODERS_PAD_A_RIGHT
#endif

#ifdef ENCODERS_PAD_B_RIGHT
#undef ENCODERS_PAD_B_RIGHT
#endif

#ifdef ENCODER_RESOLUTION_RIGHT
#undef ENCODER_RESOLUTION_RIGHT
#endif

#ifdef ENCODER_RESOLUTIONS_RIGHT
#undef ENCODER_RESOLUTIONS_RIGHT
#endif

// pins in info.json are wrong for some reason
#define ENCODERS_PAD_A { F4 }
#define ENCODERS_PAD_B { F5 }
#define ENCODER_RESOLUTION 4

#define ENCODERS_PAD_A_RIGHT { F4 }
#define ENCODERS_PAD_B_RIGHT { F5 }
#define ENCODER_RESOLUTION_RIGHT 4

#endif

#define RGBLIGHT_SLEEP
#define RGBLIGHT_LAYERS

#ifdef RGBLIGHT_ENABLE
//#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
//#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
//#define RGBLIGHT_EFFECT_SNAKE
//#define RGBLIGHT_EFFECT_KNIGHT
//#define RGBLIGHT_EFFECT_CHRISTMAS
//#define RGBLIGHT_EFFECT_STATIC_GRADIENT
//#define RGBLIGHT_EFFECT_RGB_TEST
//#define RGBLIGHT_EFFECT_ALTERNATING
//#define RGBLIGHT_EFFECT_TWINKLE

#define RGBLIGHT_LIMIT_VAL 150
#define RGBLIGHT_HUE_STEP 10
#define RGBLIGHT_SAT_STEP 17
#define RGBLIGHT_VAL_STEP 17
#endif

#ifdef RGB_MATRIX_ENABLE
#define RGB_MATRIX_SLEEP // turn off effects when suspended
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 150 // limits maximum brightness of LEDs to 150 out of 255. Higher may cause the controller to crash.

#define ENABLE_RGB_MATRIX_SOLID_COLOR
#define ENABLE_RGB_MATRIX_BREATHING
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_BREATHING
#define RGB_MATRIX_DEFAULT_ON true
#define RGB_MATRIX_DEFAULT_HUE 201
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_DEFAULT_SPD 50
#define RGBLIGHT_DISABLE_KEYCODES

#endif
